In [151]:
import sys
import os

from matplotlib import pyplot as plt
from scipy.io.wavfile import read, write
import numpy as np

sys.path.append('../../software/models/')

In [102]:
# constants 
INT16_FAC = (2 ** 15)
INT32_FAC = (2 ** 31)
INT64_FAC = (2 ** 63)
norm_fact = {'int16': INT16_FAC, 'int32': INT32_FAC, 'int64': INT64_FAC, 'float32': 1.0, 'float64': 1.0}

In [ ]:
def read_raw_y(file_path):
    if (os.path.isfile(file_path) == False):  # raise error if wrong input file
        raise ValueError("Input file is wrong")

    (fs, y) = read(file_path)
    return fs, y

In [148]:
def write_wav_file(file_path, fs, y):
    write(file_path, fs, y)

In [104]:
def get_normalized_y(raw_y):        
    normalized_raw_y = np.float32(raw_y) / norm_fact[raw_y.dtype.name]
    return normalized_raw_y

In [105]:
def read_and_normalize(file_path):
    (fs, y) = read_raw_y(file_path)
    return fs, get_normalized_y(y)

In [106]:
"""
A1-Part-1: Reading an audio file

Write a function that reads an audio file and returns 10 consecutive samples of the file starting from 
the 50001th sample. This means that the output should exactly contain the 50001th sample to the 50010th 
sample (10 samples). 

The input to the function is the file name (including the path) and the output should be a numpy array 
containing 10 samples.

If you use the wavread function from the utilFunctions module the input samples will be automatically 
converted to floating point numbers with a range from -1 to 1, which is what we want. 

Remember that in python, the index of the first sample of an array is 0 and not 1.

If you run your code using piano.wav as the input, the function should return the following 10 samples:  
array([-0.06213569, -0.04541154, -0.02734458, -0.0093997 ,  0.00769066,	0.02319407,  0.03503525, 
0.04309214, 0.04626606,  0.0441908], dtype=float32)
"""

def read_audio(input_file, offset=50000, num_of_samples=10):
    """
    Input:
        inputFile: the path to the wav file      
    Output:
        The function should return a numpy array that contains 10 samples of the audio.
    """
    (fs, raw_y) = read(input_file)
    normalized_raw_y = get_normalized_y(raw_y)
    sampled_normalized_y = normalized_raw_y[offset:offset+num_of_samples]
    return sampled_normalized_y
    

In [128]:
piano_wav = read_audio('../../sounds/piano.wav')
piano_wav

array([-0.06213379, -0.04541016, -0.02734375, -0.00939941,  0.00769043,
        0.02319336,  0.03503418,  0.04309082,  0.04626465,  0.04418945],
      dtype=float32)

In [108]:
"""
A1-Part-2: Basic operations with audio

Write a function that reads an audio file and returns the minimum and the maximum values of the audio 
samples in that file. 

The input to the function is the wav file name (including the path) and the output should be two floating 
point values returned as a tuple.

If you run your code using oboe-A4.wav as the input, the function should return the following output:  
(-0.83486432, 0.56501967)
"""
def minMaxAudio(inputFile):
    """
    Input:
        inputFile: file name of the wav file (including path)
    Output:
        A tuple of the minimum and the maximum value of the audio samples, like: (min_val, max_val)

    """
    (fs, y) = read_and_normalize(inputFile)
    return np.min(y), np.max(y)

In [109]:
minMaxAudio('../../sounds/oboe-A4.wav')

(-0.83483887, 0.56500244)

In [117]:
"""
A1-Part-3: Python array indexing

Write a function that given a numpy array x, returns every Mth element in x, starting from the 
first element.  

The input arguments to this function are a numpy array x and a positive integer M such that M < number of 
elements in x. The output of this function should be a numpy array.

If you run your code with x = np.arange(10) and M = 2, the function should return the following output: 
array([0, 2, 4, 6, 8]).
"""
def hopSamples(x,M):
    """
    Inputs:
        x: input numpy array
        M: hop size (positive integer)
    Output:
        A numpy array containing every Mth element in x, starting from the first element in x.
    """
    return x[::M]
    

In [123]:
x = np.arange(10) 
M = 2 
hopSamples(x, M)

array([0, 2, 4, 6, 8])

In [138]:
"""
A1-Part-4: Downsampling audio: Changing the sampling rate

One of the required processes to represent a signal inside a computer is sampling. The sampling rate is the number of samples obtained in one second when sampling a continuous analog signal to a discrete digital signal. As mentioned earlier, most of the time we will be working with wav audio files that have a sampling rate of 44100 Hz, which is a typical value. For some applications, changing the sampling rate of an audio signal can be necessary. This optional part shows how to do this, from a higher sampling rate to a lower one.

Complete the function downsampleAudio(inputFile,M) in the file A1Part4.py so that given an audio file, it applies downsampling by a factor of M and create a wav audio file <input_name>_downsampled.wav at a lower sampling rate.

In Part1 you learned how to read a wav file and the function from Part3 can be used to perform the downsampling of a signal contained in an array. To create a wav audio file from an array, you can use the wavwrite function from the utilFunctions module. Be careful with the sampling rate parameter since it should be different from that of the original audio.

You can test your code using the file `vibraphone-C6.wav' and a downsampling factor of M=16. 
Listen to the `vibraphone-C6_downsampled.wav' sound. What happened to the signal?
How could we avoid damaging the signal when downsampling it?
You can find some related information in https://en.wikipedia.org/wiki/Decimation_%28signal_processing%29.
"""

def downsample_audio(inputFile, M):
    """
    Inputs:
        inputFile: file name of the wav file (including path)
        	M: downsampling factor (positive integer)
    """
    (fs, x) = read_and_normalize(inputFile)
    downsampled_audio =  hopSamples(x, M)
    return fs, downsampled_audio
    

In [158]:
M = 16
fs, downsampled_vibraphone = downsample_audio('../../sounds/oboe-A4.wav', M)
new_fs = int(fs/M)ß
write_wav_file('../../sounds/original/oboe-A4_downsampled.wav', new_fs, downsampled_vibraphone)